### ISSUE TITLE
Were is main.version is the go code ? 

### ISSUE THREAD

**Issue by slashformotion** [charmbracelet/bubbletea-app-template#20]
https://github.com/charmbracelet/bubbletea-app-template/blob/6a24e23d0d3b3192aa51ae7fd89dadd1eece6f29/.goreleaser.yaml#L14

I think it will prevent the build from being successful

**Comment by caarlos0** [comment]
> I think it will prevent the build from being successful

it doesn't.

That said, that is also the default from goreleaser, so we can remove it.
